spring:
    application:
        name: @project.artifactId@
    datasource:
        # default connection pool
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        # PostgreSQL
        url: ${JDBC_URL:jdbc:postgresql://localhost:5432/mydb}
        username: ${JDBC_USERNAME:admin}
        password: ${JDBC_PASSWORD}
    jpa:
        hibernate:
            # Hibernate DDL auto: create, create-drop, validate, update
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
    main:
        banner-mode: off

app:
    db:
        init:
            enabled: false

server:
    port: ${SERVICE_PORT:10000}
    forward-headers-strategy: framework

management:
    server:
        port: 10001
    endpoints:
        web:
            base-path: /manage
            exposure:
                include: '*'
    endpoint:
        health:
            probes:
                enabled: true
    info:
        env:
            enabled: true
info:
    app:
        java:
            version: @java.version@
        encoding: @project.build.sourceEncoding@
        type: Spring Boot Web & JPA
        name: @project.name@
